/*
   Copyright 2015 Lynntech Inc. 
   Contact information:
   - Victor Palmer, 		victor.palmer[\AT]lynntech.com
   - Christian Bruccoleri, 	christian.bruccoleri[\AT]lynntech.com
   
   Research reported in this publication was supported by the National Eye Institute 
   of the National Institutes of Health under Award Number R43EY024800.
   The content is solely the responsibility of the authors and does not necessarily
   represent the official views of the National Institutes of Health.

   This code includes parts of BoofCV: https://github.com/lessthanoptimal/BoofCV
   
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

/**
 * An exception thrown when Autofocus is not supported by the Android Camera driver.
 */
package com.lynntech.cps.android.calibration;

/**
 * @author Christian Bruccoleri
 *
 */
public class AutofocusNotSupportedException extends Exception {
	
	/**
	 * A Serialization ID generated by Eclipse.
	 */
	private static final long serialVersionUID = 455631762469510300L;

	/**
	 * Default
	 */
	public AutofocusNotSupportedException() {
		super();
	}

	/**
	 * @param detailMessage
	 */
	public AutofocusNotSupportedException(String detailMessage) {
		super(detailMessage);
	}

	/**
	 * @param throwable
	 */
	public AutofocusNotSupportedException(Throwable throwable) {
		super(throwable);
	}

	/**
	 * @param detailMessage
	 * @param throwable
	 */
	public AutofocusNotSupportedException(String detailMessage,
			Throwable throwable) {
		super(detailMessage, throwable);
	}
}
